version: '3.8'
services:
  db:
    image: postgres:13
    container_name: edu_practice_db
    environment:
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: edu_password
      POSTGRES_DB: edu_practice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: